[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.83"
wasi-preview1-component-adapter-provider = "33.0.0"
wit-component = "0.235.0"
glob = "0.3.2"
xshell = "0.2.6"
