[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.83"
wasi-preview1-component-adapter-provider = "23.0.1"
wit-component = "0.214.0"
xshell = "0.2.6"
