[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.83"
wasi-preview1-component-adapter-provider = "27.0.0"
wit-component = "0.220.0"
xshell = "0.2.6"
