[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
glob = { workspace = true }
wasi-preview1-component-adapter-provider = { workspace = true }
wit-component = { workspace = true }
xshell = { workspace = true }
