[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.83"
wasm-opt = { version = "0.116.1", optional = true }
wit-component = "0.208.0"
wizer = { version = "6.0.0", optional = true }
xshell = "0.2.6"

[features]
default = []
static = ["dep:wasm-opt", "dep:wizer"]
