[package]
name = "promptkit_c_api"
version.workspace = true
edition.workspace = true

[lib]
name = "promptkit"
crate-type = ["cdylib"]

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }

[build-dependencies]
cbindgen = "0.29.0"
