[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true

[dependencies]
cbor4ii = { version = "0.3.2", features = ["serde1"] }
eventsource = { version = "0.5.0", default-features = false }
futures = { version = "0.3.30", default-features = false, features = ["std"] }
pyo3 = { version = "0.21.2", features = ["abi3"] }
serde = "1.0.199"
serde_json = "1.0.116"
thiserror = "1.0.59"
url = "2.5.0"
wasi = { workspace = true }
wasi-runtime = { path = "../wasi-runtime" }
wit-bindgen = "0.25.0"

[build-dependencies]
flate2 = "1.0.29"
tar = "0.4.40"
ureq = "2.9.7"
url = "2.5.0"
