[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true
exclude = ["/bundled", "bundle.py"]

[dependencies]
cbor4ii = { version = "0.3.2", features = ["serde1"] }
eventsource = { version = "0.5.0", default-features = false }
pyo3 = { version = "0.22.0", features = ["abi3"] }
serde = "1.0.199"
serde_json = "1.0.116"
thiserror = "2.0.0"
url = "2.5.0"
wit-bindgen = "0.34.0"
