[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true
exclude = ["/bundled", "bundle.py"]

[dependencies]
cbor4ii = { version = "1.0.0", features = ["serde1"] }
eventsource = { version = "0.5.0", default-features = false }
prost-reflect = { version = "0.15.0", features = ["serde"] }
pyo3 = { version = "0.25.1", features = ["abi3"], git = "https://github.com/brian14708/pyo3.git", branch = "wasi-0.25" }
memchr = "2.7.4"
serde = "1.0.199"
serde_json = "1.0.116"
thiserror = "2.0.0"
toml = "0.8.20"
tonic-reflection = { version = "0.13.0", default-features = false }
url = "2.5.0"
wit-bindgen = "0.42.0"
