[package]
name = "promptkit-python"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
exclude = ["/bundled", "bundle.py"]

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = { workspace = true }
eventsource = { workspace = true }
heapless = { workspace = true }
minicbor = { workspace = true }
minicbor-serde = { workspace = true, features = ["alloc"] }
pyo3 = { workspace = true, features = ["abi3"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
wit-bindgen = { workspace = true, features = ["macros"] }
