[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true

[dependencies]
cbor4ii = { version = "0.3.2", features = ["serde1"] }
pyo3 = { version = "0.20.3", features = ["abi3"] }
serde = "1.0.197"
serde_json = "1.0.114"
thiserror = "1.0.57"
url = "2.5.0"
wit-bindgen = "0.21.0"

[build-dependencies]
flate2 = "1.0.28"
tar = "0.4.40"
ureq = "2.9.6"
url = "2.5.0"
