[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true
exclude = ["/bundled"]

[dependencies]
cbor4ii = { version = "0.3.2", features = ["serde1"] }
eventsource = { version = "0.5.0", default-features = false }
futures = { version = "0.3.30", default-features = false, features = ["std"] }
pyo3 = { version = "0.22.0", features = ["abi3"] }
serde = "1.0.199"
serde_json = "1.0.116"
thiserror = "1.0.59"
url = "2.5.0"
wasi = { workspace = true }
wit-bindgen = "0.28.0"
