[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true
exclude = ["/bundled", "bundle.py"]

[dependencies]
cbor4ii = { version = "1.0.0", features = ["serde1"] }
eventsource = { version = "0.5.0", default-features = false }
prost-reflect = { version = "0.14.6", features = ["serde"] }
pyo3 = { version = "0.23.0", features = ["abi3"] }
serde = "1.0.199"
serde_json = "1.0.116"
thiserror = "2.0.0"
tonic-reflection = { version = "0.12.3", default-features = false }
url = "2.5.0"
wit-bindgen = "0.40.0"
