[package]
name = "promptkit_python"
version.workspace = true
edition.workspace = true
exclude = ["/bundled", "bundle.py"]

[lib]
crate-type = ["cdylib"]

[dependencies]
minicbor-serde = { workspace = true, features = ["alloc"] }
eventsource = { workspace = true }
prost-reflect = { workspace = true, features = ["serde"] }
pyo3 = { workspace = true, features = ["abi3"] }
memchr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tonic-reflection = { workspace = true }
url = { workspace = true }
wit-bindgen = { workspace = true, features = ["macros"] }
serde_yaml = { workspace = true }
base64 = { workspace = true }
