[project]
name = "promptkit-py"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["promptkit"]
sources = ["."]
include = ["promptkit/py.typed"]

[tool.mypy]
mypy_path = "typings"

[tool.pyright]
venvPath = "."
venv = ".venv"
stubPath = "typings"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
