[project]
name = "promptkit-py"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.1",
    "pyyaml>=6.0.2",
    "cbor2>=5.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["promptkit", "typings"]
include = ["promptkit/py.typed"]

[tool.hatch.build.targets.wheel.sources]
promptkit = "promptkit"
typings = "."

[tool.mypy]
mypy_path = "typings"

[tool.pyright]
venvPath = "."
venv = ".venv"
stubPath = "typings"
