[package]
name = "promptkit-c-api"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[lib]
name = "promptkit"
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
promptkit-cbor = { workspace = true }
promptkit-executor = { workspace = true }
promptkit-request = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[build-dependencies]
cbindgen = { workspace = true }
