[project]
name = "isola-py"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.1",
    "pyyaml>=6.0.2",
    "cbor2>=5.6.0",
    "duron>=0.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["sandbox", "typings"]
include = ["sandbox/py.typed"]

[tool.hatch.build.targets.wheel.sources]
sandbox = "sandbox"
typings = "."

[tool.mypy]
mypy_path = "typings"

[tool.pyright]
venv = ".venv"
venvPath = "../../../.."
reportMissingModuleSource = "none"
