[package]
name = "promptkit_request"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1.10.0"
futures = "0.3.31"
http = "1.2.0"
http-body = "1.0.1"
http-body-util = "0.1.2"
moka = { version = "0.12.10", features = ["future"] }
opentelemetry = "0.29.0"
opentelemetry-semantic-conventions = { version = "0.29.0", features = ["semconv_experimental"] }
pin-project-lite = "0.2.16"
reqwest = { version = "0.12.12", default-features = false, features = ["http2", "stream"] }
tokio-tungstenite = { version = "0.26.2", default-features = false, features = ["handshake"] }
tonic = { version = "0.13.0", default-features = false, features = ["channel"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.30.0"

[features]
default = ["gzip", "tls-webpki-roots"]
tls-webpki-roots = ["tls", "reqwest/rustls-tls-webpki-roots", "tonic/tls-webpki-roots"]
tls = ["reqwest/rustls-tls", "tonic/tls-ring"]
gzip = ["reqwest/gzip", "tonic/gzip"]
