[package]
name = "promptkit_executor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
bytes = "1.5.0"
coarsetime = "0.1.34"
eventsource-stream = "0.2.3"
futures-util = "0.3.30"
parking_lot = "0.12.1"
pin-project-lite = "0.2.13"
rand = "0.8.5"
reqwest = { version = "0.11.23", features = ["stream", "rustls-tls-webpki-roots"], default-features = false }
serde_json = { version = "1.0.113", features = ["raw_value"] }
sha2 = "0.10.8"
smallvec = "1.13.1"
tokio = "1.35.1"
tokio-stream = "0.1.14"
tracing = "0.1.40"
wasmtime = { version = "18.0.0", default-features = false, features = ["cranelift", "async", "parallel-compilation", "pooling-allocator"] }
wasmtime-wasi = "18.0.0"
