[package]
name = "promptkit_executor"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.79"
bytes = "1.6.0"
cap-std = "3.0.0"
coarsetime = "0.1.34"
eventsource-stream = "0.2.3"
futures-util = "0.3.30"
hex = "0.4.3"
parking_lot = "0.12.1"
pin-project-lite = "0.2.13"
rand = "0.8.5"
reqwest = { version = "0.12.1", features = ["stream", "rustls-tls-webpki-roots", "gzip"], default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["raw_value"] }
sha2 = "0.10.8"
smallvec = "1.13.2"
tempdir = "0.3.7"
thiserror = "1.0.58"
tokio = "1.36.0"
tokio-stream = "0.1.15"
tracing = "0.1.40"
wasmtime = { version = "19.0.0", default-features = false, features = ["cranelift", "async", "parallel-compilation", "pooling-allocator"] }
wasmtime-wasi = "19.0.0"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
