[package]
name = "promptkit_server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.76"
async-trait = "0.1.75"
axum = "0.7.2"
axum-extra = { version = "0.9.1", features = ["cookie"] }
axum-server = "0.6.0"
jsonwebtoken = "9.2.0"
mimalloc = { version = "0.1.39", default-features = false }
openid = "0.12.1"
prometheus-client = "0.22.0"
promptkit_executor = { version = "0.1.0", path = "../promptkit_executor" }
reqwest = { version = "0.11.23" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio", "tls-native-tls", "uuid"] }
time = "0.3.31"
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["parking_lot"] }
uuid = { version = "1.6.1", features = ["serde"] }
