[package]
name = "promptkit_server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.76"
async-trait = "0.1.75"
axum = "0.7.2"
axum-server = "0.6.0"
bytes = "1.5.0"
parking_lot = "0.12.1"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sha2 = { version = "0.10.8", features = ["asm"] }
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wasmtime = "16.0.0"
wasmtime-wasi = "16.0.0"
