[package]
name = "promptkit_trace"
version.workspace = true
edition.workspace = true

[dependencies]
fastant = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
