[package]
name = "promptkit_server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.82"
axum = { version = "0.7.5", features = ["http2"] }
bytes = "1.7.1"
cbor4ii = { version = "0.3.2", features = ["serde1"] }
coarsetime = "0.1.34"
futures-core = "0.3.30"
futures-util = "0.3.30"
http = "1.1.0"
http-body = "1.0.1"
http-body-util = "0.1.2"
mimalloc = { version = "0.1.41", default-features = false }
moka = { version = "0.12.7", features = ["future"] }
opentelemetry = "0.27.0"
opentelemetry-otlp = { version = "0.27.0", features = ["http-proto", "reqwest-client", "reqwest-rustls"] }
opentelemetry-semantic-conventions = { version = "0.27.0", features = ["semconv_experimental"] }
opentelemetry_sdk = { version = "0.27.0", features = ["rt-tokio"] }
pin-project = "1.1.5"
prometheus-client = "0.22.2"
promptkit_executor = { path = "../executor" }
promptkit_llm = { path = "../llm" }
prost = "0.13.0"
prost-types = "0.13.0"
reqwest = { version = "0.12.4", features = ["rustls-tls-webpki-roots", "gzip", "stream"], default-features = false }
serde = { version = "1.0.199", features = ["derive"] }
serde-transcode = "1.1.1"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
tonic = { version = "0.12.0", features = ["gzip"] }
tonic-reflection = "0.12.0"
tonic-web = "0.12.0"
tower-http = { version = "0.6.0", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.28.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "parking_lot"] }
url = "2.5.1"

[build-dependencies]
tonic-build = "0.12.0"
