[package]
name = "promptkit-server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["http2"] }
bytes = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
mimalloc = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["http-proto", "reqwest-client", "reqwest-rustls", "tokio"] }
opentelemetry-semantic-conventions = { workspace = true, features = ["semconv_experimental"] }
opentelemetry_sdk = { workspace = true, features = ["experimental_trace_batch_span_processor_with_async_runtime", "rt-tokio"] }
pin-project-lite = { workspace = true }
promptkit-executor = { workspace = true }
promptkit-request = { workspace = true }
promptkit-trace = { workspace = true }
promptkit-cbor = { workspace = true, features = ["prost"] }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["handshake"] }
tonic = { workspace = true, features = ["gzip", "router", "server", "tls-webpki-roots"] }
tonic-reflection = { workspace = true }
tonic-web = { workspace = true }
tower-http = { workspace = true, features = ["fs", "trace"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "parking_lot"] }
url = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
