[package]
name = "promptkit_server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.82"
axum = { version = "0.8.0", features = ["http2"] }
bytes = "1.7.1"
cbor4ii = { version = "1.0.0", features = ["serde1"] }
futures-core = "0.3.30"
futures-util = "0.3.30"
http = "1.1.0"
http-body = "1.0.1"
metrics = "0.24.1"
metrics-exporter-prometheus = { version = "0.17.0", default-features = false }
mimalloc = { version = "0.1.41", default-features = false }
opentelemetry = "0.29.0"
opentelemetry-otlp = { version = "0.29.0", features = ["http-proto", "reqwest-client", "reqwest-rustls", "tokio"], default-features = false }
opentelemetry-semantic-conventions = { version = "0.29.0", features = ["semconv_experimental"] }
opentelemetry_sdk = { version = "0.29.0", features = ["experimental_trace_batch_span_processor_with_async_runtime", "rt-tokio"] }
pin-project = "1.1.5"
promptkit_executor = { path = "../executor" }
promptkit_request = { version = "0.1.0", path = "../request" }
promptkit_trace = { path = "../trace" }
prost = "0.13.0"
prost-types = "0.13.0"
serde = { version = "1.0.199", features = ["derive"] }
serde-transcode = "1.1.1"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
tokio-tungstenite = { version = "0.26.2", default-features = false, features = ["handshake"] }
tonic = { version = "0.13.0", features = ["gzip", "tls-webpki-roots"] }
tonic-reflection = "0.13.0"
tonic-web = "0.13.0"
tower-http = { version = "0.6.0", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.30.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "parking_lot"] }
url = "2.5.1"

[build-dependencies]
tonic-build = "0.13.0"
