name: Server (UI)

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - .github/**
      - ui/**
      - apis/**
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
        working-directory: ui
      - run: bun run build
        working-directory: ui
      - run: bun run lint
        working-directory: ui
