[package]
name = "promptkit_llm"
version.workspace = true
edition.workspace = true

[dependencies]
sentencepiece = { version = "0.11.2", features = ["static"] }
serde = { version = "1.0.200", features = ["derive"] }
thiserror = "1.0.60"
